#!/bin/bash

cd ../

if [ ! -d build ]; then
    mkdir build
fi

cd build

cmake -D arm_compile="ARM" ..
make clean
make

if [ ! -d ../bin ]; then
     mkdir ../bin
fi

cp garage_monitor_server ../bin/.
