#!/bin/bash

echo "Build test files."

cd ../

if [ ! -d build ]; then
    mkdir build
fi

cd build

cmake -D arm_compile="TEST" ..
make clean
make

if [ ! -d ../bin ]; then
     mkdir ../bin
fi

cp *_test ../bin/.
